/**
 * Builds the public font registry from /registry source files.
 *
 * Emits:
 *   apps/web/public/r/registry.json        full catalog
 *   apps/web/public/r/<slug>.json          one item per font
 *   apps/web/public/r/fonts/<slug>/*       woff2 files + license
 *   apps/web/app/preview-fonts.css         @font-face rules for site previews
 *   registry/schema.json                   JSON Schema for font.json autocomplete
 *
 * Run with: node scripts/build-registry.ts (Node >= 22.6 type stripping)
 */
import { cp, mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { zipSync } from "fflate";
import {
  fontJsonSchema,
  fontSchema,
  type Font,
  type Registry,
} from "../packages/registry/src/index.ts";

const ROOT = path.resolve(import.meta.dirname, "..");
const SRC_DIR = path.join(ROOT, "registry", "fonts");
const WEB_DIR = process.env.ZELTO_WEB_DIR ?? path.join(ROOT, "apps", "web");
const OUT_DIR = path.join(WEB_DIR, "public", "r");
const CSS_OUT = path.join(WEB_DIR, "app", "preview-fonts.css");
const HOMEPAGE = "https://fonts.zelto.app";

async function loadFonts(): Promise<Font[]> {
  const slugs = (await readdir(SRC_DIR, { withFileTypes: true }))
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  const fonts: Font[] = [];
  const errors: string[] = [];

  for (const slug of slugs) {
    const jsonPath = path.join(SRC_DIR, slug, "font.json");
    if (!existsSync(jsonPath)) {
      errors.push(`${slug}: missing font.json`);
      continue;
    }
    const raw = JSON.parse(await readFile(jsonPath, "utf8"));
    const parsed = fontSchema.safeParse(raw);
    if (!parsed.success) {
      errors.push(`${slug}: ${parsed.error.issues.map((i) => `${i.path.join(".")}: ${i.message}`).join("; ")}`);
      continue;
    }
    const font = parsed.data;
    if (font.name !== slug) {
      errors.push(`${slug}: font.json name "${font.name}" does not match directory name`);
      continue;
    }
    for (const file of font.files) {
      const expectedPrefix = `/r/fonts/${slug}/`;
      if (!file.path.startsWith(expectedPrefix)) {
        errors.push(`${slug}: file path "${file.path}" must start with "${expectedPrefix}"`);
        continue;
      }
      const onDisk = path.join(SRC_DIR, slug, "files", path.basename(file.path));
      if (!existsSync(onDisk)) {
        errors.push(`${slug}: referenced file not found on disk: ${onDisk}`);
      }
    }
    if (!existsSync(path.join(SRC_DIR, slug, "files", "OFL.txt"))) {
      errors.push(`${slug}: missing files/OFL.txt (license must ship with the font)`);
    }
    fonts.push(font);
  }

  if (errors.length > 0) {
    console.error("Registry validation failed:\n" + errors.map((e) => `  ✗ ${e}`).join("\n"));
    process.exit(1);
  }
  return fonts;
}

function stripSchemaField(font: Font): Omit<Font, "$schema"> {
  const { $schema, ...rest } = font;
  return rest;
}

function previewCss(fonts: Font[]): string {
  const blocks = fonts.flatMap((font) =>
    font.files.map((file) => {
      const weight = typeof file.weight === "number" ? String(file.weight) : file.weight;
      return [
        "@font-face {",
        `  font-family: "zelto-${font.name}";`,
        `  src: url("${file.path}") format("woff2");`,
        `  font-weight: ${weight};`,
        `  font-style: ${file.style};`,
        "  font-display: swap;",
        "}",
      ].join("\n");
    }),
  );
  return `/* Generated by scripts/build-registry.ts — do not edit. */\n\n${blocks.join("\n\n")}\n`;
}

async function main() {
  const fonts = await loadFonts();

  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_DIR, { recursive: true });

  const items = fonts.map(stripSchemaField);
  const registry: Registry = { name: "zelto", homepage: HOMEPAGE, items };

  await writeFile(path.join(OUT_DIR, "registry.json"), JSON.stringify(registry, null, 2));
  for (const item of items) {
    await writeFile(path.join(OUT_DIR, `${item.name}.json`), JSON.stringify(item, null, 2));
  }
  await writeFile(path.join(OUT_DIR, "schema.json"), JSON.stringify(fontJsonSchema, null, 2));

  for (const font of fonts) {
    const filesDir = path.join(SRC_DIR, font.name, "files");
    await cp(filesDir, path.join(OUT_DIR, "fonts", font.name), { recursive: true });

    // direct-download zip (woff2 is already compressed — store only)
    const zipEntries: Record<string, Uint8Array> = {};
    for (const entry of await readdir(filesDir)) {
      zipEntries[`${font.name}/${entry}`] = new Uint8Array(await readFile(path.join(filesDir, entry)));
    }
    await writeFile(path.join(OUT_DIR, `${font.name}.zip`), zipSync(zipEntries, { level: 0 }));
  }

  await mkdir(path.dirname(CSS_OUT), { recursive: true });
  await writeFile(CSS_OUT, previewCss(fonts));

  await writeFile(
    path.join(ROOT, "registry", "schema.json"),
    JSON.stringify(fontJsonSchema, null, 2),
  );

  console.log(`✓ Registry built: ${fonts.length} fonts → ${path.relative(ROOT, OUT_DIR)}`);
}

await main();
